import './globals.css'
import type { Metadata } from 'next'
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <title>Imperial Consórcio</title>
      </head>
      <body>        
        <Header />
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  )
}
